catalog:
  build: ./catalog
  ports:
    - "8000:8000"
  links:
    - redis
  command: ./main
integrationtest:
  build: ./integration-test
  links:
    - catalog
  command: raco test main.rkt
redis:
  image: redis
